<?php
namespace compact\logging;

use compact\logging\recorder\impl\FileRecorder;
use compact\utils\Random;
/**
 * Test class for FileRecorder.
 * Generated by PHPUnit on 2014-11-19 at 14:50:35.
 */
class FileRecorderTest extends \PHPUnit_Framework_TestCase
{

    private $path;
    /**
     *
     * @var FileRecorder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->path = new \SplFileInfo(sys_get_temp_dir() . '/compact-log-' . Random::alphaNum(6) . '/test.log' );
        $this->object = new FileRecorder($this->path);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * Test that when recording to a non (yet) existing dir, it will be created automatically
     */
    public function testNewLogDir(){
        $this->object->record(__METHOD__, 1);
    }
    
}
