<?php
namespace compact\utils;

use testutils\mvvm\TestModel;
use testutils\mvvm\TestModelConfiguration;
/**
 * Test class for HttpRequest.
 * Generated by PHPUnit on 2014-11-19 at 14:41:13.
 */
class ModelUtilsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $_POST = array();
    }

    private function mockPost($key, $value)
    {
        $_POST[$key] = $value;
    }
    
    
    public function testGetPost(){
        $this->mockPost(TestModel::FIELD1, "value1");
        
        $model = ModelUtils::getPost(new TestModelConfiguration());
        
        $this->assertEquals("value1", $model->get(TestModel::FIELD1));
    }
   
}
