<?php
namespace compact\io\writer;

/**
 * Test class for StreamWriter.
 * Generated by PHPUnit on 2014-11-19 at 14:43:59.
 */
class StreamWriterTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var StreamWriter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StreamWriter("php://output");
        $this->object->open();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers compact\io\writer\StreamWriter::createReader
     *
     * @todo Implement testCreateReader().
     */
    public function testCreateReader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\io\writer\StreamWriter::getBytesWritten
     *
     * @todo Implement testGetBytesWritten().
     */
    public function testGetBytesWritten()
    {
        $write = "line";
        
        ob_start();
        $this->object->write($write);
        $output = ob_get_clean();
        
        $this->object->close();
        $this->assertEquals(4, $this->object->getBytesWritten());
    }

    /**
     * @covers compact\io\writer\StreamWriter::open
     *
     * @todo Implement testOpen().
     */
    public function testOpen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\io\writer\StreamWriter::truncate
     *
     * @todo Implement testTruncate().
     */
    public function testTruncate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    public function testWrite()
    {
        $write = "line1-line2";
        
        ob_start();
        $this->object->write($write);
        $output = ob_get_clean();
        
        $this->object->close();
        $this->assertEquals($write, $output);
    }

    /**
     * @covers compact\io\writer\StreamWriter::writeLine
     *
     * @todo Implement testWriteLine().
     */
    public function testWriteLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
?>
