<?php
namespace compact\handler;

/**
 * Test class for AssertHandler.
 * Generated by PHPUnit on 2014-11-19 at 14:10:31.
 */
class AssertHandlerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers compact\handler\AssertHandler::disable
     */
    public function testDisable()
    {
        // enable assert with custom trigger
        AssertHandler::disable();
        
        assert(false); // trigger assert
    }

    /**
     * @covers compact\handler\AssertHandler::enable
     */
    public function testEnable()
    {
        $trigger = false;
        
        // enable assert with custom trigger
        AssertHandler::enable(function () use(&$trigger)
        {
            $trigger = true;
        });
        
        assert(false); // trigger assert
        
        $this->assertTrue($trigger, 'Assert was not triggered');
    }
}
