<?php
namespace compact\io\reader;

/**
 * Test class for StreamReader.
 * Generated by PHPUnit on 2015-06-12 at 15:36:46.
 */
class StreamReaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StreamReader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // open up this file for reading
        $this->object = new StreamReader(__FILE__);
        $this->object->open();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        if ($this->object->isOpened()){
            $this->object->close();
        }
    }

    /**
     * @covers compact\io\reader\StreamReader::read
     * @todo Implement testRead().
     */
    public function testRead()
    {
        // read <?php
        $line = $this->object->read(7); 
        
        $this->assertEquals(strlen($line), $this->object->getBytesRead(), $line . " was read....");
    }

    /**
     * @covers compact\io\reader\StreamReader::readLine
     * @todo Implement testReadLine().
     */
    public function testReadLine()
    {
       // read <?php
        $line = $this->object->readLine(); 
        
        // + 2 for \r\n
        $this->assertEquals(strlen($line)+strlen(PHP_EOL), $this->object->getBytesRead(), $line . " was read....");
    }

    /**
     * @covers compact\io\reader\StreamReader::readLineAt
     * @todo Implement testReadLineAt().
     */
    public function testReadLineAt()
    {
        // read <?php
        $line = $this->object->readLineAt(1); 
        
        // + 2 for \r\n
        $this->assertEquals(strlen($line)+strlen(PHP_EOL), $this->object->getBytesRead(), $line . " was read....");
    }
}
?>
