<?php
namespace compact\logging;

use compact\mvvm\impl\Model;
/**
 * Test class for Model.
 * Generated by PHPUnit on 2014-11-19 at 14:50:35.
 */
class ModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Model();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    public function testSet0Value(){
        $this->object->{'test'} = 0;
        
        $this->assertEquals(0, $this->object->{'test'});
    }
}
