<?php
namespace compact\http;

/**
 * Test class for HttpResponse.
 * Generated by PHPUnit on 2014-11-19 at 14:41:13.
 */
class HttpResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var HttpResponse
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpResponse();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers compact\http\HttpResponse::addHeader
     *
     * @todo Implement testAddHeader().
     */
    public function testAddHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::disableCache
     *
     * @todo Implement testDisableCache().
     */
    public function testDisableCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::flush
     *
     * @todo Implement testFlush().
     */
    public function testFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::getCharSet
     *
     * @todo Implement testGetCharSet().
     */
    public function testGetCharSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::getContentType
     *
     * @todo Implement testGetContentType().
     */
    public function testGetContentType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::getStatusCode
     *
     * @todo Implement testGetStatusCode().
     */
    public function testGetStatusCode()
    {
        $code = $this->object->getStatusCode();
        
        $this->assertEquals(200, $code, 'Default status code should be 200');
    }

    /**
     * @covers compact\http\HttpResponse::getWriter
     *
     * @todo Implement testGetWriter().
     */
    public function testGetWriter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::isHeaderSend
     *
     * @todo Implement testIsHeaderSend().
     */
    public function testIsHeaderSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::redirect
     *
     * @todo Implement testRedirect().
     */
    public function testRedirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::setCharSet
     *
     * @todo Implement testSetCharSet().
     */
    public function testSetCharSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::setContentType
     *
     * @todo Implement testSetContentType().
     */
    public function testSetContentType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::setEnableCache
     *
     * @todo Implement testSetEnableCache().
     */
    public function testSetEnableCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::setHeader
     *
     * @todo Implement testSetHeader().
     */
    public function testSetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers compact\http\HttpResponse::setStatusCode
     *
     * @todo Implement testSetStatusCode().
     */
    public function testSetStatusCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
?>
