<?php
namespace compact\filesystem;

/**
 * Test class for Mimetype.
 * Generated by PHPUnit on 2015-06-15 at 21:05:07.
 */
class MimetypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Mimetype
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mimetype();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers compact\filesystem\Mimetype::get
     */
    public function testGet()
    {
        $this->assertTrue(Mimetype::get() instanceof Mimetype);
    }

    /**
     * @covers compact\filesystem\Mimetype::getType
     */
    public function testGetType()
    {
        $type = $this->object->getType(new \SplFileInfo(__FILE__));
        $this->assertEquals('text/plain', $type, 'Got other type: ' . $type);
    }

    /**
     * @covers compact\filesystem\Mimetype::getTypeForExtension
     * @todo Implement testGetTypeForExtension().
     */
    public function testGetTypeForExtension()
    {
        $type = $this->object->getTypeForExtension("jpg");
        
        $this->assertEquals('image/jpeg', $type, 'Got other type: ' . $type);
    }
}
