<?php
namespace compact\io\reader;

/**
 * Test class for StreamReader.
 * Generated by PHPUnit on 2015-06-12 at 15:36:46.
 */
class AbstractStreamAccesserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StreamReader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // open up this file for reading
        $this->object = new StreamReader(__FILE__);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        if ($this->object->isOpened()){
            $this->object->close();
        }
    }

    /**
     * @covers compact\io\reader\StreamReader::getBytesRead
     * @todo Implement testGetBytesRead().
     */
    public function testGetBytesRead()
    {
        $this->object->readLine();
        
        
        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers compact\io\reader\StreamReader::read
     * @todo Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers compact\io\reader\StreamReader::readLine
     * @todo Implement testReadLine().
     */
    public function testReadLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers compact\io\reader\StreamReader::readLineAt
     * @todo Implement testReadLineAt().
     */
    public function testReadLineAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
